[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run db:generate", "npm run build"]

[phases.setup]
cmds = ["npx prisma migrate deploy || true"]

[start]
cmd = "npm start"

